// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using robot_controller_api.Persistence;

#nullable disable

namespace robot_controller_api.Migrations
{
    [DbContext(typeof(RobotContext))]
    [Migration("20260906115916_AddRobotCommandStepsAndCompositeDirections")]
    partial class AddRobotCommandStepsAndCompositeDirections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("robot_controller_api.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Columns")
                        .HasColumnType("integer")
                        .HasColumnName("columns");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsSquare")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasColumnName("is_square")
                        .HasComputedColumnSql("((rows > 0) AND (rows = columns))", true);

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.HasKey("Id");

                    b.ToTable("map", (string)null);
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("description");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsMoveCommand")
                        .HasColumnType("boolean")
                        .HasColumnName("is_move_command");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("MovementDirection")
                        .HasColumnType("integer")
                        .HasColumnName("movement_direction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("robot_command", null, t =>
                        {
                            t.HasCheckConstraint("ck_robot_command_movement_direction", "(is_move_command = false AND movement_direction IS NULL) OR (is_move_command = true AND movement_direction IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommandSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancellation_requested");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("failure_reason");

                    b.Property<int?>("FinalX")
                        .HasColumnType("integer")
                        .HasColumnName("final_x");

                    b.Property<int?>("FinalY")
                        .HasColumnType("integer")
                        .HasColumnName("final_y");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("StartX")
                        .HasColumnType("integer")
                        .HasColumnName("start_x");

                    b.Property<int>("StartY")
                        .HasColumnType("integer")
                        .HasColumnName("start_y");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_robot_command_sequence_map_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_robot_command_sequence_active_user")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("robot_command_sequence", (string)null);
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommandSequenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("command_name");

                    b.Property<DateTime?>("ExecutedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_date");

                    b.Property<bool>("IsExecuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_executed");

                    b.Property<int>("MovementDirection")
                        .HasColumnType("integer")
                        .HasColumnName("movement_direction");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("RobotCommandId")
                        .HasColumnType("integer")
                        .HasColumnName("robot_command_id");

                    b.Property<int>("SequenceId")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_id");

                    b.HasKey("Id");

                    b.HasIndex("RobotCommandId");

                    b.HasIndex("SequenceId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_robot_command_sequence_item_sequence_order");

                    b.ToTable("robot_command_sequence_item", (string)null);
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommandStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("MovementDirection")
                        .HasColumnType("integer")
                        .HasColumnName("movement_direction");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("RobotCommandId")
                        .HasColumnType("integer")
                        .HasColumnName("robot_command_id");

                    b.HasKey("Id");

                    b.HasIndex("RobotCommandId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_robot_command_step_command_order");

                    b.ToTable("robot_command_step", (string)null);
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int?>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int?>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_robot_state_user_id");

                    b.ToTable("robot_state", (string)null);
                });

            modelBuilder.Entity("robot_controller_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("robot_controller_api.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ExpiresDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_date");

                    b.Property<DateTime?>("LastSeenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_date");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_date");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommandSequence", b =>
                {
                    b.HasOne("robot_controller_api.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("robot_controller_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommandSequenceItem", b =>
                {
                    b.HasOne("robot_controller_api.Models.RobotCommand", "RobotCommand")
                        .WithMany()
                        .HasForeignKey("RobotCommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("robot_controller_api.Models.RobotCommandSequence", "Sequence")
                        .WithMany("Items")
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RobotCommand");

                    b.Navigation("Sequence");
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommandStep", b =>
                {
                    b.HasOne("robot_controller_api.Models.RobotCommand", "RobotCommand")
                        .WithMany("Steps")
                        .HasForeignKey("RobotCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RobotCommand");
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotState", b =>
                {
                    b.HasOne("robot_controller_api.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("robot_controller_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("robot_controller_api.Models.UserSession", b =>
                {
                    b.HasOne("robot_controller_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommand", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("robot_controller_api.Models.RobotCommandSequence", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
